# Generated by Django 5.1.1 on 2024-10-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('back_end_skills', models.ManyToManyField(related_name='back_end_coders', to='filters.skill')),
                ('front_end_skills', models.ManyToManyField(related_name='front_end_coders', to='filters.skill')),
            ],
        ),
    ]
